# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, max_length=30)),
                ('desc', models.CharField(blank=True, max_length=10000)),
                ('likes', models.CharField(default='0', max_length=10)),
                ('dislikes', models.CharField(default='0', max_length=10)),
                ('comment1', models.CharField(blank=True, max_length=1000)),
                ('comment2', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
